#!/bin/bash

cd $(dirname $0)

./sync_repo Tizen:Common ia32-wayland
./sync_repo Tizen:Common x86_64-wayland
./sync_repo Tizen:Common x86_64-x11

#./sync_repo Tizen:Common:devel ia32-wayland
./sync_repo Tizen:Common:devel x86_64-wayland
./sync_repo Tizen:Common:devel x86_64-x11

./sync_repo Tizen:Common:multiuser x86_64-wayland

./sync_repo Tizen:Common:sandbox x86_64-wayland
