#!/usr/bin/node


/* 
 * testkit-generator tool : to generate a testkit xml files based on a directory tree
 */

var TKIT   = require('libtestkit')
var path   = require('path')
var log4js = require('log4js')
var logger = log4js.getLogger("tkitgen");
var ArgumentParser = require('argparse').ArgumentParser;

// ---------------- Begining of the program ---------------- //

var parser = new ArgumentParser({
    version: '1.0.0',
	addHelp: true,
	description: 'Tool to generate testkit xml files'
});

parser.addArgument(
	['-d', '--database'],
	{
		help: 'Path of the tests database',
		dest: 'database',
		required: true
	}
);

parser.addArgument(
	['-p', '--profile'],
	{
		help: 'Tizen profile. Ex: common or ivi',
		dest: 'profile',
		required: true
	}
);

parser.addArgument(
	['-s', '--suite'],
	{
		help: 'Suite shortname',
		dest: 'suite',
		required: true
	}
);

parser.addArgument(
	['-o', '--outdir'],
	{
		help: 'Output directory of the generated testkit xml files',
		dest: 'outdir',
		required: true
	}
);

var args = parser.parseArgs();

logger.info("testkit generation started");
logger.debug ("generation requested with the following arguments:\n", args);
TKIT.TestKit.createXMLFiles(args.database, args.profile, args.suite, args.outdir);
