#!/bin/bash

export PATH=/sbin:/usr/sbin:$PATH

if [ $(id -u) -ne 0 ]; then
	echo "You must be root !" >&2
	exit 1
fi

img=$1
if [ ! -f "$img" ]; then
	echo "Usage: $(basename $0) <usb image>" >&2
	exit 1
fi

outdir=${2:-.}
if [ ! -d "$outdir" ]; then
	echo "Invalid output dir $outdir" >&2
	exit 1
fi

loopdev=
mntdir=
function cleanup () {
	set +e

	echo "Cleanup..." >&2
	if [ -n "$mntdir" ]; then
		echo "Unmounting $mntdir" >&2
		umount $mntdir
		rmdir $mntdir
	fi

	if [ -n "$loopdev" ]; then
		echo "Removing loop device $loopdev" >&2
		kpartx -d $img
		losetup -D
	fi
}
trap "cleanup" STOP INT QUIT EXIT

set -e

#kpartx -a -s $img
loopdev=/dev/mapper/$(kpartx -avs $img | awk '{print $3}')

echo "Image $img mounted as loop device $loopdev" >&2

mntdir=$(mktemp -d /var/tmp/$(basename $0).XXXXXX)

mount $loopdev $mntdir

echo "$loopdev mounted in $mntdir" >&2

#cp -v $mntdir/syslinux/vmlinuz0 $outdir/vmlinuz
#cp -v $mntdir/syslinux/initrd0.img $outdir/initrd.img
cp -v $mntdir/LiveOS/squashfs.img $outdir/squashfs.img

rm -rf $outdir/liveusb
mkdir -p $outdir/liveusb
rsync -Pav $mntdir/ $outdir/liveusb/

